/**
 * Writes the Content-Security-Policy into the built site's `_headers` file.
 *
 * The policy has to name the SHA-256 of two inline things the build emits:
 *
 *   1. the pre-paint theme guard in index.html (an inline <script>), and
 *   2. the `onload` attribute the critical-CSS step adds to the deferred
 *      stylesheet link (`this.media='all'`), which needs 'unsafe-hashes'.
 *
 * Both are hashed from the BUILT file rather than hand-copied, so editing the
 * guard can never leave a stale hash behind — a stale hash would block the
 * guard and bring back the theme flash the guard exists to prevent.
 *
 * Static headers (caching, the rest of the security set) live in netlify.toml;
 * Netlify merges the two sources.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const OUT_DIR = 'dist/professional-porfolio/browser';
const indexPath = join(OUT_DIR, 'index.html');

if (!existsSync(indexPath)) {
  console.error(`gen-headers: ${indexPath} not found — run the build first.`);
  process.exit(1);
}

const html = readFileSync(indexPath, 'utf8');

/**
 * Hash the way the BROWSER will.
 *
 * The HTML tokenizer normalises CRLF (and a lone CR) to LF before a script's
 * text ever reaches the CSP check. So a file written with Windows line endings
 * hashes differently on disk than it does in the parser, and the policy then
 * blocks the very script it was generated from. The symptom is quiet — one
 * console message and the theme flash the guard exists to prevent — which is
 * exactly why this is computed rather than hand-copied.
 */
const sha256 = (source) =>
  `'sha256-${createHash('sha256').update(source.replace(/\r\n?/g, '\n'), 'utf8').digest('base64')}'`;

/** Inline <script> bodies, skipping src= references and non-executable types (ld+json). */
const scriptHashes = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)]
  .filter(
    ([, attrs, body]) =>
      body.trim() && !/\bsrc=/.test(attrs) && !/type=["'](?!text\/javascript)/.test(attrs),
  )
  .map(([, , body]) => sha256(body));

/** Inline event-handler attributes, which need 'unsafe-hashes' alongside their hash. */
const handlerHashes = [...html.matchAll(/\bon[a-z]+="([^"]*)"/g)].map(([, code]) => sha256(code));

const policy = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  // Angular writes component styles into the document as <style> elements at
  // runtime, and the critical-CSS step inlines more at build time. Neither can
  // be hashed ahead of time, so inline styles stay allowed; no external style
  // origin is.
  "style-src 'self' 'unsafe-inline'",
  `script-src 'self' ${[...scriptHashes, ...(handlerHashes.length ? ["'unsafe-hashes'", ...handlerHashes] : [])].join(' ')}`.trim(),
  "connect-src 'self'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# GENERATED by scripts/gen-headers.mjs — do not edit by hand.
# Static headers live in netlify.toml; this file carries only the CSP, whose
# hashes are computed from the built index.html.
/*
  Content-Security-Policy: ${policy}
`;

writeFileSync(join(OUT_DIR, '_headers'), headers, 'utf8');
console.log(
  `gen-headers: wrote _headers (${scriptHashes.length} inline script hash(es), ${handlerHashes.length} handler hash(es)).`,
);
